package com.eigenbound.domain.puzzle.cryptography;

import java.time.Duration;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.Random;

import com.eigenbound.domain.puzzle.MiniPuzzle;
import com.eigenbound.domain.puzzle.PuzzleOption;
import com.eigenbound.domain.puzzle.PuzzleTopic;
import com.eigenbound.domain.puzzle.generation.GeneratedMiniPuzzle;
import com.eigenbound.domain.puzzle.generation.MiniPuzzleGenerator;

/**
 * Generates deterministic Caesar-cipher mini-puzzles.
 *
 * <p>
 * The generator selects the solution first, encrypts it and then builds three
 * distinct distractors. This constructive approach guarantees that every
 * generated puzzle has a valid solution.
 * </p>
 */
public final class CaesarCipherPuzzleGenerator
        implements MiniPuzzleGenerator {

    private static final int MIN_DIFFICULTY = 1;
    private static final int MAX_DIFFICULTY = 5;
    private static final int OPTION_COUNT = 4;

    private static final List<String> DIFFICULTY_ONE_MESSAGES = List.of(
            "VECTOR",
            "MATRIX",
            "SCALAR",
            "BASIS",
            "GRAPH",
            "CIPHER");

    private static final List<String> DIFFICULTY_TWO_MESSAGES = List.of(
            "EIGENVALUE",
            "SUBSPACE",
            "TRANSFORM",
            "DIAGONAL",
            "INVERSE",
            "MODULAR");

    private static final List<String> DIFFICULTY_THREE_MESSAGES = List.of(
            "LINEAR MAP",
            "NULL SPACE",
            "COLUMN SPACE",
            "SECRET SHIFT",
            "GRAPH PATH",
            "STATE MACHINE");

    private static final List<String> DIFFICULTY_FOUR_MESSAGES = List.of(
            "EIGEN VECTOR",
            "CHANGE OF BASIS",
            "MODULAR INVERSE",
            "DIRECTED GRAPH",
            "RANDOM VARIABLE",
            "BINARY STRING");

    private static final List<String> DIFFICULTY_FIVE_MESSAGES = List.of(
            "LINEAR TRANSFORMATION",
            "CONDITIONAL PROBABILITY",
            "CHARACTERISTIC VALUE",
            "FINITE STATE MACHINE",
            "FREQUENCY ANALYSIS",
            "EIGENBOUND EXPEDITION");

    private final CaesarCipher cipher;

    /**
     * Creates a generator with the standard Caesar-cipher implementation.
     */
    public CaesarCipherPuzzleGenerator() {
        this(new CaesarCipher());
    }

    /**
     * Creates a generator with an explicit cipher dependency.
     *
     * @param cipher cipher used to construct puzzle messages
     */
    public CaesarCipherPuzzleGenerator(
            CaesarCipher cipher) {
        this.cipher = Objects.requireNonNull(
                cipher,
                "Caesar cipher cannot be null");
    }

    /**
     * Returns the academic topic generated by this implementation.
     */
    @Override
    public PuzzleTopic topic() {
        return PuzzleTopic.CRYPTOGRAPHY;
    }

    /**
     * Generates a reproducible Caesar-cipher puzzle.
     */
    @Override
    public GeneratedMiniPuzzle generate(
            long seed,
            int difficulty) {
        validateDifficulty(difficulty);

        Random random = new Random(seed);
        List<String> messages = messagesFor(difficulty);

        String solution = randomElement(
                random,
                messages);

        int shift = generateShift(
                random,
                difficulty);

        String encryptedMessage = cipher.encrypt(
                solution,
                shift);

        AnswerOptions answerOptions = generateOptions(
                random,
                messages,
                solution);

        MiniPuzzle puzzle = new MiniPuzzle(
                puzzleId(
                        seed,
                        difficulty),
                topic(),
                prompt(
                        encryptedMessage,
                        shift),
                answerOptions.options(),
                answerOptions.correctOptionId(),
                explanation(
                        encryptedMessage,
                        solution,
                        shift),
                difficulty,
                timeLimitFor(difficulty));

        return new GeneratedMiniPuzzle(
                puzzle,
                seed);
    }

    /**
     * Builds four shuffled answer options containing one known solution.
     */
    private AnswerOptions generateOptions(
            Random random,
            List<String> messages,
            String solution) {
        List<String> distractors = new ArrayList<>(messages);
        distractors.remove(solution);
        Collections.shuffle(
                distractors,
                random);

        List<String> optionTexts = new ArrayList<>();
        optionTexts.add(solution);
        optionTexts.addAll(
                distractors.subList(
                        0,
                        OPTION_COUNT - 1));

        Collections.shuffle(
                optionTexts,
                random);

        List<PuzzleOption> options = new ArrayList<>();
        String correctOptionId = null;

        for (int index = 0; index < optionTexts.size(); index++) {
            String optionId = Character.toString(
                    'A' + index);

            String optionText = optionTexts.get(index);

            options.add(
                    new PuzzleOption(
                            optionId,
                            optionText));

            if (optionText.equals(solution)) {
                correctOptionId = optionId;
            }
        }

        return new AnswerOptions(
                List.copyOf(options),
                Objects.requireNonNull(
                        correctOptionId,
                        "Generated options must contain the solution"));
    }

    /**
     * Selects the message catalog associated with a difficulty level.
     */
    private List<String> messagesFor(
            int difficulty) {
        return switch (difficulty) {
            case 1 -> DIFFICULTY_ONE_MESSAGES;
            case 2 -> DIFFICULTY_TWO_MESSAGES;
            case 3 -> DIFFICULTY_THREE_MESSAGES;
            case 4 -> DIFFICULTY_FOUR_MESSAGES;
            case 5 -> DIFFICULTY_FIVE_MESSAGES;
            default -> throw new IllegalArgumentException(
                    "Unsupported puzzle difficulty: "
                            + difficulty);
        };
    }

    /**
     * Generates larger possible shifts as difficulty increases.
     */
    private int generateShift(
            Random random,
            int difficulty) {
        int maximumShift = switch (difficulty) {
            case 1 -> 5;
            case 2 -> 9;
            case 3 -> 13;
            case 4 -> 19;
            case 5 -> 25;
            default -> throw new IllegalArgumentException(
                    "Unsupported puzzle difficulty: "
                            + difficulty);
        };

        return random.nextInt(maximumShift) + 1;
    }

    /**
     * Reduces available time as intellectual difficulty increases.
     */
    private Duration timeLimitFor(
            int difficulty) {
        long seconds = 26L - difficulty * 3L;

        return Duration.ofSeconds(seconds);
    }

    /**
     * Creates a stable identifier without signed-seed formatting ambiguity.
     */
    private String puzzleId(
            long seed,
            int difficulty) {
        return "caesar-"
                + Long.toUnsignedString(seed)
                + "-d"
                + difficulty;
    }

    private String prompt(
            String encryptedMessage,
            int shift) {
        return "Decrypt this Caesar message using shift "
                + shift
                + ": "
                + encryptedMessage;
    }

    private String explanation(
            String encryptedMessage,
            String solution,
            int shift) {
        return "Moving every letter "
                + shift
                + " positions backward transforms "
                + encryptedMessage
                + " into "
                + solution
                + ".";
    }

    private String randomElement(
            Random random,
            List<String> elements) {
        return elements.get(
                random.nextInt(elements.size()));
    }

    private void validateDifficulty(
            int difficulty) {
        if (difficulty < MIN_DIFFICULTY
                || difficulty > MAX_DIFFICULTY) {
            throw new IllegalArgumentException(
                    "Puzzle difficulty must be between one and five");
        }
    }

    /**
     * Keeps generated options together with the identifier of their solution.
     */
    private record AnswerOptions(
            List<PuzzleOption> options,
            String correctOptionId) {
    }
}